To make and run testme.c:
	gcc -o testme testme.c
	./testme

The inputChar() function selects a random character from its list of lowercase
and special characters that a specifically tested within the testme() function.
The inputStr() function simply makes a string of length 5 with random lowercase
characters.

The random tester first works by changing the state variable within testme()
when the inputChar() function returns a specific special character.  Once all
9 of those selected special characters have been generated by inputChar(), the
random tester will produce the error when inputStr() generates with a string
of 'reset', with those characters in that order.