/**
*       author: Kayla Fitzsimmons
*       course: Software Engineering II
*        term: Fall 2015
*        file: randomhistory.c
*       description: file describing results of random tests
**/
**Please note that most of the code I wrote to randomize the game state can be found in the file randomize.c**
**To print out more output set the MORE flag at the top of each file to 1**  

                    ADVENTURE CARD
 Becuase I was aware of bug that I added to the adventure card function which results in only one treasure being 
 removed from the deck instead of two, I decided to work on creating really good random deck, discard, and supply piles
 so that I could test that the non-treasure cards were going to the player's discard pile in many situations. 

My tests count wheither or not the right number of cards are located in the discard pile after play_adventurer is called.
 When I first executed my random tests, I found that whenever the two treasure cards were not at the 
 top of the deck, the test would fail. After examining the adventure card function's code, I realized that the 
 discardCount was never being incremented. This bug has been documented as bug no. 10 in the bugs.c
 file. Bug no. 10 surprised me, because I had not intentionally added it to the code in the previous assignments
 and I also somehow missed it during unit testing.  
 
Code coverage for this test was about 21% with 19% branch coverage. That was to be expected, considering the
cards were not going into the discard pile. This is a good example of how less than optimal test coverage
can signal that there is a problem in the code you are testing. 
 
 
                        MINE CARD
I made sure that these tests were valid by taking the rules from the game specificaton. The mine card allows the
user to trash one treasure card in their hand (trash card) and gain a card from the supply that no more than 3
coin more than the card being trashed. The tests are generated by calling the same state setting functions as
for the Adventurer card.
 
 I found it most important to test that the logic of the card was sound, the random tests for 
  Mine card are based on the following three rules:
  
 In my tests;
 A trash card is valid if it is a copper, silver, or gold card
 A gain card is valid if it is a copper, silver, or gold card
 The cost is valid if the gain card costs at most 3 more coin than the trash card
 
 
 The tests are guaged based on wheither or not the actual results
 match the corresponding expected results,
 
 A. The trash card is valid and the gain card is invalid
      expects -1
 B. The trash card is invalid and the gain card is valid
      expects -1
 C. If Both cards are valid
    a. checks if the cost of the gain card is at most 3 more
       trash card
       expects 0
 D. If both cards are invalid
    a. checks wheither or not the cost is valid 
    expects -1 
    
The tests I ran resulted in the discovery of bug 11. I found that the mine card in the game was allowing the 
user to gain any kind of card with a valid cost, instead of a treasure card specifically. The test reproduction information
is in the bugs1.c file. For this test alone, the branch coverage was 28.00%. This was a definit improvement over the unit tests, for which the
aggregate branch coverage was about 40%. 
    
    
    
    