/*
Brian Tiegs
CS 362 - Assignment 4

randomhistory.c

********************************************************************************

Development of Random Testers

Random testers were developed for the adventurer card and the treasure map card. Both implementations were done by randomizing the game state, saving the pre game state, running the function under test and comparing the post-state to the pre-state for correctness. A seed is used to generate the random game state. In both implementations, the seed starts at 1 and increments 10000 times, therefore, each time the program runs the same data is generated. The benefit of this is if an error is found, the seed number can be used to recreate the game state. To test more randomly generated states the SEED_START would need to be changed.

To generate the random game state, first the number of players was randomized from 2 to 4. The kingdom cards were randomized using the selectKingdomCards function and the seed. Since we are testing specific cards, the tester checks the selected cards for the card under test and, if not found, the tester adds it. The game was then initialized using the function initializeGame(). All decks, hands and discard piles were randomly generated for all players with estate cards, treasure cards and the selected kingdom cards. The deck count, hand count and discard count was also randomly generated. These values were set by randomly generating a number from 0 to 150. 150 was selected because it would be highly unlikely this number would be exceeded in a normal game. Also the supplyCount was randomly generated by randomly generating a number from 0 to 20 for each card.

After the testers randomly generated the game state with the given restrictions, the pre game state was saved using memcpy. Next the game state was used to run the function under test. The pre-state and the post-state was then compared to test the correctness of the function. Once the tests were completed, the test outputs if the tests passed or failed. The seed is then incremented and the tester repeats.

********************************************************************************

Correctness of Specification

Selecting the correct test conditions is essential for a tester to be effective. For my random testers to pass a test, the following conditions must be met:

Random Test Adventurer Card
-game state is unchanged (numPlayers, outpostPlayed, outpostTurn, whoseTurn, phase, numActions, coins, numBuys, playedCardCount, embargoTokens, supplyCount)
-other player's states are unchanged (deck, hand, discard, deckCount, handCount, discardCount)
-treasure cards added to player's hand
-discarded cards from deck moved to discard pile

Random Test Treasure Map Card
-game state is unchanged (numPlayers, outpostPlayed, outpostTurn, whoseTurn, phase, numActions, coins, numBuys, playedCardCount, embargoTokens)
-other player's states are unchanged (deck, hand, discard, deckCount, handCount, discardCount)
-correct value returned when the number of treasure maps in the player's hand is less than 2
-player's state is unchanged when the number of treasure maps in the player's hand is less than 2
-correct value returned when the number of treasure maps in the player's hand is 2 or greater
-correct number of gold cards added to player's hand when the number of treasure maps in the player's hand is 2 or greater
-player's discard pile is unchanged when the number of treasure maps in the player's hand is 2 or greater
-treasure map cards discarded from hand when the number of treasure maps in the player's hand is 2 or greater
-gold cards removed from supply count when the number of treasure maps in the player's hand is 2 or greater

********************************************************************************

Coverage

Results for random testers:

	Testing complete for "Adventurer Card"
		Summary:
		Tests run: 10000
		Tests passed: 0
		Tests failed: 10000

		File 'dominion.c'
		Lines executed:22.80% of 579
		Branches executed:20.14% of 417
		Taken at least once:18.71% of 417
		Calls executed:10.53% of 95

	Testing complete for "Treasure Map Card"
		Summary:
		Tests run: 10000
		Tests passed: 9802
		Tests failed: 198

		File 'dominion.c'
		Lines executed:24.18% of 579
		Branches executed:26.62% of 417
		Taken at least once:18.94% of 417
		Calls executed:12.63% of 95

Results for unit tests from Assignment 3:

	Testing complete for "Adventurer Card"
		Summary:
		Tests run: 39
		Tests passed: 24
		Tests failed: 15

		cardtest1: Adventurer Card
		Lines executed:5.53% of 579
		Branches executed:8.87% of 417
		Taken at least once:3.12% of 417
		Calls executed:3.16% of 95

	Testing complete for "Treasure Map Card"
		Summary:
		Tests run: 146
		Tests passed: 138
		Tests failed: 8

		cardtest4: Treasure Map Card
		Lines executed:7.25% of 579
		Branches executed:10.31% of 417
		Taken at least once:4.56% of 417
		Calls executed:5.26% of 95

	dominion.c had 21.8% statement coverage for the adventurer card random tester and 24.18% for the treasure map card random tester. This is a substantial increase from the previous unit tests that only achieved 5.53% and 7.25%. This is most likely due to the call to initializeGame. In addition, both random testers had 100% branch and statement coverage for the functions under test. When comparing to the previous unit tests, 100% branch and statement coverage was only achieved with the treasure map card but the adventurer card was significantly less. Although I wrote code to give 100% coverage, a bug prevented the statements from being called. My random tester was able to call the statements even in the presence of the bug. As a result, the random testers gave complete coverage.

	The adventurer card random tester failed all tests. This is because of a substantial bug I introduced for assignment 2. Since the number of failed tests was so high, I decided to correct the bug and rerun the random tester. In this scenario most tests passed however there were a few that failed. When analyzing the game state it was obvious the error occurred when there were no treasure cards in the deck or discard pile. These bugs were also identified in the previous unit tests.

	The treasure map card random tester passed 9802/10000 tests. The test that failed was the removal of the treasure cards from the hand. This bug was also identified in the previous unit tests.

	********************************************************************************

	Conclusion

	The effort required to implement the random testers was much less when compared to the unit tests for assignment 3. Instead of being concerned with implementing a specific game state to test a condition, the game state was simply randomized and the pre-state was compared with the post-state. Although the randomization took a while to set up, the same code could be reused for all card tests. The only modifications needed would be which conditions to test the pre and post states. This would save a significant amount of time when implementing testers for all of the functions in dominion.c.

	The coverage was also substantially better for the random testers. Despite a bug that prevented my unit test from assignment 3 to give complete coverage, the random tester was able to get complete branch and statement coverage. Although the random testers did not identify any new bugs, it did detect all of the same bugs previously identified. Overall the random testers proved to be a very powerful tool for finding bugs.

*/
