Brian Lamere
CS362_400
Fall 2015
8 NOV 2015

Assignment 4 - Random Testers for 2 Dominion cards

        The first function I chose to write a random tester for was the playVillageCard() function. This one was pretty easy to write, and a good one to start with, because there are only two primary things happening with it: +1 card to the player's hand, and +2 actions. I also added a couple supporting functions at this point, one of which I wish I had thought to do for the last assignment. It is a function that prints out the key values of the gameState struct, including the cards in the collection of the player. This function could probably tweaked in a multitude of ways so that I could dial it in to just show specific states (e.g., add a parameter to show the supply count of a particular card, or add parameters for certain flags to include/exclude certain entities like the hand, the deck, or the discard pile, etc.) making it more universal, but for this assignment it worked okay.
        The other function I added was a gameState randomizer that randomizes just the variables key to the particular function being tested. For this function, I am randomizing the number of actions, the number of coins, and the cards in all the player's hands, and then in the actual tester function, because those are basically the only variables that should be changing when the village card is played.
       One other thing I did was basically ignore a bug that I discovered in last week's testing: I figured since I already know it exists, there is no reason to keep failing tests because of it. (The particular bug is the one where a card can be played by the function even if it isn't in the player's hand). But I wanted the player's hand to be correct, at least, so in the random tester, after randomizing but before playing the village card, I make sure the player has the village card in their hand by manually putting it there. Then, I save the game state in a different structure, play the card, then assert that the player's hand count incremented by 1 and that the number of actions increased by 2. Also, using my gameState-printer function, I discovered that the playVillageCard() function puts the "played" village card in the playedCards pile, so I also assert that that happens.
        All of the above results in the test running multiple times with 0 errors. Which is curious, given that I had introduced a bug myself: namely, drawing 2 cards for the player instead of one. The reason this doesn't get caught has to be because the village card itself gets discarded by the play function (decrementing handCount), so adding 2 would result in an overall +1 handCount, which is what I asserted. So at this point, I am a bit uncertain: is my test wrong or is the function itself wrong. Because, technically, the player should have 1 additional card, not just replace the village card with another card. (So maybe the "bug" I introduced actually "fixed" one that was already present).
       Either way, though, the other random tester was for the adventurer card, for which I pretty much used the same boiler-plate code from the first test, just changing what gets randomized and what gets asserted per the specs of the card. 
       The randomizer stays the same, more or less, but I also give the player 5 random treasure cards to make sure that they have enough of them in the deck to meet the action of the card (and I am just realizing now that a good test assertion would probably be to see what happens if the player actually doesn't have 2 Treasure cards in their hand), then I shuffle the deck.
       As for the assertions that are made after the card is played, first I make sure that the player actually has +2 cards in their hand. Then I assert that the count of coin cards in their hand is +2. I had another assertion to check that the adventure card itself gets either discarded or put in the played card pile, but it got triggered in every run, so I've' just commented it out, because it was adding too much "noise" to the test output.
       The curious thing about this tester is that it definitely identifies that something is amiss with the function, but I have to do some investigation to get to the heart of it. The bug I introduced was having the function check for the "smithy" card instead of the "silver" card when "revealing" cards from the deck for treasure cards, so the problem is, sometimes it works, but sometimes it doesn't. So my tester identifies that sometimes the player doesn't have 2 treasure cards, but sometimes they don't have +2 cards in the hand as well. Setting VERBOSE mode and looking at the actual cards in the hand before & after is the key to finding what's happening.

       As for code coverage, every line in the playVillageCard() function gets executed an equal number of times (which is to be expected, since it never branches).  And in the playAdventureCard() function, during the 48,248 times the function gets called, every branch and statement is covered (including shuffling the deck when empty) at least a couple thousand times. The tester itself is called hundreds of times for multiple player counts inside the driver function, which I think is sufficient to identify the extant bugs.

